# This is a basic workflow to help you get started with Actions

name: Build & Deploy to Digital Ocean

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ conversion ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'debug'
jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Build and deploy Sparlay website
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            pm2 delete SpaDev
            cd /var/www/spa-dev/
            git pull
            npm run build
            echo -e "PORT=3001" > .env
            pm2 --name SpaDev start npm -- start